# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-alb-target-group-cloudwatch-sns-alarms
  description: Terraform module to create CloudWatch Alarms on ALB Target level metrics.
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-module, aws, cloudwatch-alarms, sns, alb, target-group, ingress, hcl2



